<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="L089344" name="NewMaven.qaClickAcademy" tests="5" failures="1" timestamp="08 Jan 2019 18:28:36 GMT" time="45.851" errors="0">
  <testcase name="validateText" time="0.240" classname="NewMaven.qaClickAcademy">
    <failure type="java.lang.AssertionError" message="expected [AN ACADEMY TO LEARN EVERYTHING ABOUT TESING] but found [AN ACADEMY TO LEARN EVERYTHING ABOUT TESTING]">
      <![CDATA[java.lang.AssertionError: expected [AN ACADEMY TO LEARN EVERYTHING ABOUT TESING] but found [AN ACADEMY TO LEARN EVERYTHING ABOUT TESTING]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at NewMaven.qaClickAcademy.validateText(qaClickAcademy.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateText -->
  <testcase name="clickLogin" time="8.634" classname="NewMaven.qaClickAcademy"/>
  <testcase name="clickLogin" time="10.608" classname="NewMaven.qaClickAcademy"/>
  <testcase name="clickLogin" time="7.536" classname="NewMaven.qaClickAcademy"/>
  <testcase name="basePageNavigation" time="18.833" classname="NewMaven.qaClickAcademy"/>
</testsuite> <!-- NewMaven.qaClickAcademy -->
